# Generated by Django 3.0.3 on 2020-05-06 16:52

import SmartDjango.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_user_enter_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', SmartDjango.models.fields.IntegerField(unique=True)),
                ('password', SmartDjango.models.fields.CharField(default=None, max_length=5, null=True)),
                ('member_num', SmartDjango.models.fields.IntegerField(default=0)),
                ('speaker', SmartDjango.models.fields.IntegerField(default=1)),
                ('create_time', SmartDjango.models.fields.DateTimeField(auto_now_add=True)),
                ('member_a', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_a', to='Room.member')),
                ('member_b', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_b', to='Room.member')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='Room.member')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=None, null=True)),
                ('create_time', SmartDjango.models.fields.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Room.member')),
            ],
            options={
                'abstract': False,
                'default_manager_name': 'objects',
            },
        ),
    ]
