# Generated by Django 3.0.3 on 2020-05-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enter_room',
            field=models.BooleanField(default=False),
        ),
    ]
